### ISSUE TITLE
How to implement demo effect

### ISSUE THREAD

**Issue by yang-junhua** [facebookresearch/segment-anything#698]
Demo url：[](https://segment-anything.com/demo)
![pic](https://github.com/facebookresearch/segment-anything/assets/37500822/4c43ef3a-43a1-4371-99ec-6a791dfba4ea)
Can you tell me how to achieve the image effect? Thank you so much.

**Comment by heyoeyo** [comment]
It would depend on how you're presenting the image (i.e. where is the UI being provided?). If you try the 'cut-out' feature on that demo page, you can directly copy the CSS that's applied to the little cut-outs that appear on the far left menu:
```css
.sticker:hover, .sticker-select {
    filter: drop-shadow(0.25rem 0.25rem 1px #2962d9)
    drop-shadow(-0.25rem 0.25rem 1px #2962d9)
    drop-shadow(0.25rem -0.25rem 1px #2962d9)
    drop-shadow(-0.25rem -0.25rem 1px #2962d9);
}
```
You have to dig through the browser inspect window (i.e. hit F12 on chrome/firefox at least) a bit, but you can toggle that CSS on/off and see the effect appear/disappear. So that's one way to do it, if you're using a web-based UI.

If you wanted to do it within python, there's an explanation of how to modify one of the notebooks to get a similar-ish outline effect in issue #589.
